const fs=require('fs'),path=require('path'),esbuild=require('esbuild');const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'www');fs.mkdirSync(out,{recursive:true});fs.cpSync(path.join(root,'backend/public/preview'),out,{recursive:true});
const generated=path.join(__dirname,'generated');fs.mkdirSync(generated,{recursive:true});
let jj=fs.readFileSync(path.join(root,'backend/jinjiang.js'),'utf8').split('function createRouter')[0].replace("const axios = require('axios');",'').replace("require('cheerio')","require('cheerio/slim')").replace("const express = require('express');",'');jj+='\nmodule.exports={parseBook,parseSearch,parseAuthors,parseAuthorBooks,encodeKeyword};';fs.writeFileSync(path.join(generated,'jinjiang.cjs'),jj);
let fq=fs.readFileSync(path.join(root,'backend/fanqie.js'),'utf8');fq=fq.slice(fq.indexOf('const validId'),fq.indexOf('function createRouter'));fq="const cheerio=require('cheerio/slim');\n"+fq+'\nmodule.exports={parseBook,parseAuthorBooks,searchUrl,parseSearchResponse};';fs.writeFileSync(path.join(generated,'fanqie.cjs'),fq);
let cp=fs.readFileSync(path.join(root,'backend/changpei.js'),'utf8');cp="const cheerio=require('cheerio/slim');\n"+cp.slice(cp.indexOf('const validId'),cp.indexOf('async function getPage'));cp+='\nmodule.exports={parseBook,parseSearch,parseAuthors,parseAuthorBooks,endpoint};';fs.writeFileSync(path.join(generated,'changpei.cjs'),cp);
let overview=fs.readFileSync(path.join(root,'backend/overview.js'),'utf8');const prompt=overview.match(/role:'system',content:('(?:[^'\\]|\\.)*')/)[1];fs.writeFileSync(path.join(generated,'prompt.cjs'),'module.exports='+prompt+';');
esbuild.buildSync({entryPoints:[path.join(__dirname,'runtime.js')],outfile:path.join(out,'mobile.js'),bundle:true,platform:'browser',format:'iife',inject:[path.join(__dirname,'shim.js')],minify:true});
let html=fs.readFileSync(path.join(out,'index.html'),'utf8').replace('阅读档案预览','阅读档案').replace('<script src="ai.js">','<script>window.OCR_ASSET_GZIP=false;</script><script src="mobile.js"></script><script src="ai.js">').replace('width=device-width, initial-scale=1','width=device-width, initial-scale=1, viewport-fit=cover');fs.writeFileSync(path.join(out,'index.html'),html);
let app=fs.readFileSync(path.join(out,'app.js'),'utf8').replace('当前为 Web 开发预览；原版本书架数据未迁移。','书架保存在本机；可导出备份或导入电脑预览版的备份。').replace("$('#export').onclick=()=>{","$('#export').onclick=async()=>{if(window.Mobile){try{await Mobile.exportBackup({version:1,books});}catch(e){toast('导出失败：'+e.message);}return;}");
app=app.replace("function settings(){","function settings(){").replace("$('#export').onclick=async", "window.Mobile?.settingsExtras();\n $('#export').onclick=async");
fs.writeFileSync(path.join(out,'app.js'),app);
fs.appendFileSync(path.join(out,'style.css'),'\nheader{padding-top:calc(17px + env(safe-area-inset-top))}nav{padding-bottom:max(12px,env(safe-area-inset-bottom))}main{padding-bottom:calc(110px + env(safe-area-inset-bottom))}\n');
const vendor=path.join(out,'vendor');fs.mkdirSync(vendor,{recursive:true});for(const [dest,src] of [['ocr','tesseract.js/dist'],['ocr-core','tesseract.js-core']])fs.cpSync(path.join(root,'backend/node_modules',src),path.join(vendor,dest),{recursive:true});fs.mkdirSync(path.join(vendor,'ocr-data'),{recursive:true});for(const lang of ['chi_sim','eng'])fs.copyFileSync(path.join(root,'backend/node_modules/@tesseract.js-data',lang,'4.0.0',lang+'.traineddata.gz'),path.join(vendor,'ocr-data',lang+'.traineddata.gz'));console.log('Mobile assets built; no server files or keys copied.');

const zlib=require('zlib');for(const lang of ['chi_sim','eng']){const gz=path.join(vendor,'ocr-data',lang+'.traineddata.gz');fs.writeFileSync(gz.slice(0,-3),zlib.gunzipSync(fs.readFileSync(gz)));fs.unlinkSync(gz);}
