const test=require('node:test'),assert=require('node:assert/strict');
const ui=require('../public/preview/archive-ui'),cp=require('../changpei'),fq=require('../fanqie'),ocr=require('../public/preview/ocr-parser');
test('字数显示保留精确值，近似值不伪造精度',()=>{assert.equal(ui.wordCount(240170),'24万（240,170）');assert.equal(ui.wordCount(0),'0 字');assert.equal(ui.wordCount(null),'字数未提供');assert.equal(ui.wordCount('24.0万'),'24.0万');});
test('搜索高亮转义 HTML、支持多处和正则特殊字符',()=>{assert.equal(ui.highlight('<b>a+b a+b</b>','a+b'),'&lt;b&gt;<mark>a+b</mark> <mark>a+b</mark>&lt;/b&gt;');assert.equal(ui.highlight('Test test','TEST'),'<mark>Test</mark> <mark>test</mark>');assert.equal(ui.highlight('<img>',' '),'&lt;img&gt;');});
test('搜索可展示命中的旧笔记，并且排序不改变存储顺序',()=>{const b={overview:'最新总览',entries:[{text:'很早的群像感受'},{text:'新笔记'}]};assert.equal(ui.excerpt(b,'群像'),'很早的群像感受');const books=[{title:'乙',updatedAt:1,wordCount:2,status:'想看'},{title:'甲',updatedAt:2,wordCount:1,status:'刚开始看'}];assert.equal(ui.sortBooks(books,'words')[0].title,'乙');assert.equal(ui.sortBooks(books,'updated')[0].title,'甲');assert.equal(books[0].title,'乙');assert.notEqual(ui.stateCode('刚开始看'),ui.stateCode('想看'));});
test('刷新仅合并书目资料，保留阅读状态、全部笔记和空缺原文案',()=>{const entries=[{text:'旧笔记'}],book={sourceId:'123',platform:'长佩文学',title:'书',summary:'旧文案',entries,status:'刚开始看',overview:'总览',revision:2,updatedAt:100};ui.mergeMetadata(book,{sourceId:'123',platformCode:'changpei',wordCount:240170,serialStatus:'完结',summary:'',entries:[],status:'看完',updatedAt:200});assert.equal(book.wordCount,240170);assert.equal(book.summary,'旧文案');assert.equal(book.entries,entries);assert.equal(book.status,'刚开始看');assert.equal(book.updatedAt,100);assert.throws(()=>ui.mergeMetadata(book,{sourceId:'456',platform:'长佩文学'}));});
test('长佩资料隔离字段，纯文本化文案，验证作品身份',()=>{const raw={code:200,data:{novel_id:8879,novel_name:'入睡指南',author_nickname:'作者',novel_info:'<p>第一段</p><script>bad()</script><p>第二段</p>',novel_wordnumber:140556,novel_process:'完结',chapterContent:'不可返回'}};const b=cp.parseBook(raw,'8879');assert.equal(b.title,'入睡指南');assert.equal(b.wordCount,140556);assert.ok(b.summary.includes('\n'));assert.ok(!b.summary.includes('bad'));assert.equal(b.chapterContent,undefined);assert.throws(()=>cp.parseBook(raw,'111'));assert.throws(()=>cp.endpoint('book',{id:'https://example.com'}));assert.throws(()=>cp.endpoint('search',{keyword:'x',page:-1}));});
test('长佩搜索、作者结果与番茄响应校验',()=>{assert.equal(cp.parseSearch({code:200,data:{list:[{novel_id:1,novel_name:'书',novel_author:'甲'}]}},'甲').length,1);assert.throws(()=>cp.parseSearch({code:500}));assert.equal(cp.parseAuthors({code:200,data:{list:[{user_id:215,user_nickname:'卡比丘'}]}}).authors[0].externalUrl,'https://www.gongzicp.com/zone/user-215.html');assert.equal(fq.parseSearchResponse({code:0,data:{search_book_data_list:[{book_id:'7218822722090961958',book_name:'书'}]}}).results[0].sourceId,'7218822722090961958');assert.throws(()=>fq.parseSearchResponse(''));assert.throws(()=>fq.parseSearchResponse({code:0}));});
test('OCR 无空间块时识别明确书名、精确字数，平台冲突留空',()=>{const r=ocr.parse({text:'长佩文学\n书名：入睡指南\n作者：卡比丘\n字数：140,556\n完结',confidence:95});assert.equal(r.platform,'changpei');assert.equal(r.title,'入睡指南');assert.equal(r.wordCount,140556);assert.equal(r.serialStatus,'完结');assert.equal(ocr.parse({text:'长佩文学 番茄小说'}).platform,'');assert.equal(ocr.parse({text:'字数：24.0万字'}).wordCount,'24.0万');});
test('AI 总览接受新增的刚开始看状态',async()=>{const app=require('express')();app.use('/api/ai',require('../overview').createRouter({getKey:()=> 'test',post:async()=>({data:{choices:[{finish_reason:'stop',message:{content:'刚读开头。'}}]}})}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{const res=await fetch('http://127.0.0.1:'+server.address().port+'/api/ai/overview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'书',status:'刚开始看',entries:[{text:'刚读开头',createdAt:Date.now()}]})});assert.equal(res.status,200);}finally{server.close();}});

test('原文链接保留已有地址，缺失时仅按已知平台和有效作品 ID 恢复',()=>{
 assert.equal(ui.sourceUrl({sourceUrl:'https://example.com/book?id=1'}),'https://example.com/book?id=1');
 assert.equal(ui.sourceUrl({platform:'晋江文学城',sourceId:'9299461'}),'https://www.jjwxc.net/onebook.php?novelid=9299461');
 assert.equal(ui.sourceUrl({platformCode:'fanqie',sourceId:'7218822722090961958'}),'https://fanqienovel.com/page/7218822722090961958');
 assert.equal(ui.sourceUrl({platform:'长佩文学',sourceId:'8879'}),'https://www.gongzicp.com/novel-8879.html');
 for(const book of [{sourceUrl:'javascript:alert(1)'},{platform:'晋江',sourceId:'1&evil=2'},{platform:'未知',sourceId:'123'},{platform:'晋江'}])assert.equal(ui.sourceUrl(book),'');
});
